# Generated by Django 4.1.3 on 2022-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usd',
            field=models.IntegerField(blank=True, default=100000),
        ),
    ]
