# Generated by Django 4.1.3 on 2022-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unft',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
